  # ------------------------------------------------------------------------------
  traefik-acme:
    image: traefik
    command:
      --web --docker --docker.watch --docker.exposedbydefault=false --logLevel=DEBUG
      --acme --acme.acmelogging=true --acme.email=${TRAEFIK_ACME_EMAIL}
      --acme.onhostrule --acme.ondemand
      --acme.storage=/acme/certs.json --acme.entrypoint=https
      --defaultEntryPoints=http,https
      --entryPoints='Name:http Address::80 Redirect.EntryPoint:https'
      --entryPoints='Name:https Address::443 TLS'
    restart: always
    labels:
      - "traefik.enable=false"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /dev/null:/traefik.toml
      - ./var/data/acme:/acme
    networks:
      default:
        aliases:
          - traefik
