version: '2.1'

networks:
  default:
    driver: bridge

services:

  # ------------------------------------------------------------------------------
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./var/data/db:/var/lib/postgresql/data
      - ./var/data/db-backup:/opt/backup
      - ./var/data/db-share:/opt/share
      - ./var/data/db-init:/docker-entrypoint-initdb.d/
#    ports:
#      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${PG_DB_PASS}
      - TZ=${TZ}
      - LANG=${PG_ENCODING}
      - DCAPE_DB_DUMP_DEST=/opt/backup
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres", "-h", "db"]
      interval: 2s
      timeout: 3s
      retries: 3
    stop_grace_period: 5s
    stop_signal: SIGINT


