  # ------------------------------------------------------------------------------
  traefik:
    image: traefik:1.4
    command:
      --web --docker --docker.watch --docker.exposedbydefault=false --logLevel=DEBUG

#--docker.constraints  = ["tag==hel*rld", "tag!=rev-*-beta"]

    restart: always
    labels:
      - "traefik.enable=false"
    ports:
      - "${TRAEFIK_PORT}:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /dev/null:/traefik.toml

