global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  web:
    address: "0.0.0.0:80"
    forwardedHeaders:
      insecure: true
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: false

  websecure:
    address: "0.0.0.0:443"
    forwardedHeaders:
      insecure: true
    http:
      tls:
        certResolver: letsEncrypt
        domains:
          - main: "=DCAPE_DOMAIN="
            sans:
              - "*.=DCAPE_DOMAIN="

certificatesResolvers:
  letsEncrypt:
    acme:
      email: ***-admin@change.me-***
      storage: /etc/traefik/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: pdns
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false
     # TODO: cli version does not work
    constraints: "Label(`dcape.traefik.tag`,`=DCAPE_TAG=`)"
    endpoint: "unix:///var/run/docker.sock"

  file:
    directory: /etc/traefik/custom
    watch: true

api:
  insecure: false

ping:
  manualRouting: true

log:
  level: DEBUG
