  # ------------------------------------------------------------------------------
  cis:
    image: nginx:1.13-alpine
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${CIS_HOST}"
      - "traefik.port=80"
    depends_on:
      - webtail
      - webhook
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./var/data/cis/html:/usr/share/nginx/html:ro
      - ./var/data/cis/htpasswd:/etc/nginx/htpasswd
      - ./var/data/cis/nginx.conf:/etc/nginx/conf.d/default.conf:ro


  # ------------------------------------------------------------------------------
  webtail:
    image: lekovr/webtail:${CIS_WEBTAIL_VER}
    restart: always
#    ports:
#      - "8081:8080"
    labels:
      - "traefik.enable=false"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./var/log:/var/log
    command: --root /var/log/webhook --lines 200 --host ${CIS_HOST}

  # ------------------------------------------------------------------------------
  webhook:
    image: wpalmer/webhook
    restart: always
    labels:
      - "traefik.enable=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./var/data/cis/hooks:/etc/webhook:ro
      - ./var/log/webhook:/opt/dcape/var/log/webhook
      - ./var/apps:/opt/dcape/var/apps
    command: -hooks /etc/webhook/hooks.json -hotreload -nopanic -verbose -header Content-Type=application/json
    environment:
      - DISTRO_ROOT=/opt/dcape/var/apps
      - DISTRO_CONFIG=.env
      - SSH_KEY_NAME=hook

