  # ------------------------------------------------------------------------------
  cis:
    image: nginx:1.13-alpine
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${CIS_HOST}"
      - "traefik.port=80"
    depends_on:
      - webtail
      - webhook
    volumes:
      - ./var/data/cis/html:/usr/share/nginx/html:ro
      - ./var/data/cis/htpasswd:/etc/nginx/htpasswd
      - ./var/data/cis/nginx.conf:/etc/nginx/conf.d/default.conf:ro


  # ------------------------------------------------------------------------------
  webtail:
    image: lekovr/webtail
    restart: always
    labels:
      - "traefik.enable=false"
    volumes:
      - ./var/log:/var/log/webtail
    command: --root /var/log/webtail --lines 200

  # ------------------------------------------------------------------------------
  webhook:
    image: wpalmer/webhook
    restart: always
    labels:
      - "traefik.enable=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./var/data/cis/hooks:/etc/webhook
    command: -hooks /etc/webhook/hooks.json -hotreload -nopanic -verbose -header Content-Type=application/json

