  # ------------------------------------------------------------------------------
  cis:
    image: nginx:1.19.4-alpine
    restart: always
    depends_on:
      - narra
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cis.rule=Host(`${CIS_HOST}`)"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./apps/cis/html:/usr/share/nginx/html:ro
      - ./apps/cis/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./var/data/cis/hook.pub:/data/hook.pub:ro

  # ------------------------------------------------------------------------------
  narra:
    image: dopos/narra:${CIS_NARRA_VER}
    restart: always
    command:
      --as.host http://${GITEA_HOST} --as.cookie_sign ${CIS_SIGN_KEY} --as.cookie_crypt ${CIS_CRYPT_KEY}
      --as.client_id ${AUTH_CLIENT_ID} --as.client_key ${AUTH_CLIENT_KEY}
      --as.my_url=http://${CIS_HOST} --as.do401 --as.url_header X-Forwarded-Uri
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.narra.rule=Host(`${CIS_HOST}`) && Path(`/login`,`/auth`)"
      - "traefik.http.services.narra.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.narra.forwardauth.address=http://${CIS_HOST}/auth"
      - "traefik.http.middlewares.narra.forwardauth.authResponseHeaders=X-Username"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

