  # ------------------------------------------------------------------------------
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VER}
    ports:
      - "9000"
    labels:
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.redirect.entryPoint=${REDIR_ENTRY}"
      - "traefik.frontend.rule=Host:${PORTAINER_HOST}"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./var/data/portainer:/data
