  # ------------------------------------------------------------------------------
  gitea:
    image: gitea/gitea:latest
#    image: gitea/gitea:1.1.3
    ports:
      - "${GITEA_SSH_PORT}:22"
    volumes:
      - ./var/data/gitea:/data
      - ./var/log/gitea:/data/log
    restart: always
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:${GITEA_HOST}"
    environment:
      - TZ=${TZ}

