  # ------------------------------------------------------------------------------
  gitea:
    image: gitea/gitea:${GITEA_VER}
    restart: always
    ports:
      - "${GITEA_SSH_PORT}:22"
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.http.routers.gitea.entrypoints=web"
      - "traefik.http.routers.gitea.rule=Host(`${GITEA_HOST}`)"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
    environment:
      - TZ=${TZ}
    volumes:
      - ./var/data/gitea:/data
      - ./var/log/gitea:/data/log
      - ./var/data/gitea-app-data:/app/gitea/data
